Update main_webclouditaklmpk4.yml

diff --git a/.github/workflows/main_webclouditaklmpk4.yml b/.github/workflows/main_webclouditaklmpk4.yml
--- a/.github/workflows/main_webclouditaklmpk4.yml
+++ b/.github/workflows/main_webclouditaklmpk4.yml
@@ -23,12 +23,11 @@ jobs:
         with:
           node-version: '22.x'
 
-     - name: npm install, build, and test
-        run: |
-         npm ci
-         npm run build --if-present || echo "No build step"
-         npm run test --if-present || echo "Skipping tests"  # Tambahkan ini supaya tidak error
-
+      -  name: npm install, build, and test
+          run:|
+          npm ci
+          npm run build --if-present || echo "No build step"
+          npm run test --if-present || echo "Skipping tests"  # Tambahkan ini supaya tidak error
       - name: Zip artifact for deployment
         run: zip release.zip ./* -r
 
